permalink: /:year/:month/:title 

safe: true
lsi: false
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true

title : Alex Boyd
author :
  name : Alex Boyd
  email : alex.boyd@outlook.com
  github : aaboyd
  twitter : boydale1
  bitbucket : boydale1
  gplus : 101836723454902363467

production_url : http://username.github.io

comments :
  disqus :
    short_name : alexboydblog
           
analytics :
  provider : google 
  google : 
    tracking_id : 'UA-123-12'
    
sharing :
  provider : true