permalink: /:year/:month/:title

timezone: America/New_York
lsi: false
exclude: ["README.md", "Blog.sublime-project", "run.sh", "CNAME"]
encoding: utf-8
highlighter: pygments

url : http://alexboyd.me
title : Alex Boyd
author :
  name : Alex Boyd
  email : alex.boyd@outlook.com
  github : aaboyd
  twitter : boydale1
  bitbucket : boydale1
  gplus : 101836723454902363467

markdown: kramdown
