permalink: /:year/:month/:title 

lsi: false
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true

url : http://aaboyd.github.io
title : Alex Boyd
author :
  name : Alex Boyd
  email : alex.boyd@outlook.com
  github : aaboyd
  twitter : boydale1
  bitbucket : boydale1
  gplus : 101836723454902363467

comments :
  disqus :
    short_name : alexboydblog
           
analytics :
  google : 
    tracking_id : 'UA-34607589-1'
    
sharing :
  provider : true