permalink: /:year/:month/:title 

lsi: false
exclude: ["README.md"]
pygments: true
encoding: utf-8

url : http://alexboyd.me
title : Alex Boyd
author :
  name : Alex Boyd
  email : alex.boyd@outlook.com
  github : aaboyd
  twitter : boydale1
  bitbucket : boydale1
  gplus : 101836723454902363467

markdown: kramdown